
import bi from './bi.json'
import bs from './bs.json'
import cg from './cg.json'
import ci from './ci.json'
import di from './di.json'
import fa from './fa.json'
import fc from './fc.json'
import fi from './fi.json'
import gi from './gi.json'
import go from './go.json'
import gr from './gr.json'
import hi from './hi.json'
import hi2 from './hi2.json'
import im from './im.json'
import io from './io.json'
import io5 from './io5.json'
import md from './md.json'
import ri from './ri.json'
import rx from './rx.json'
import si from './si.json'
import sl from './sl.json'

export {  bi, bs, cg, ci, di, fa, fc, fi,gi ,go, gr, hi, hi2, im, io, io5, md, ri, rx, si, sl}
